### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by jn2clark** [jxmorris12/cde#3]
Hello! This is really interesting - great work! I was wondering if the training data was available? 

Thanks!

**Comment by jxmorris12** [comment]
All the training data is open-source (Nomic training datasets and BGE). I'll post a link on my own HuggingFace profile and send it to you by the end of this week!

**Comment by jn2clark** [comment]
Great, thanks!

**Comment by jxmorris12** [comment]
https://huggingface.co/datasets/jxm/nomic_embed_unsupervised
https://huggingface.co/datasets/jxm/nomic_embed_supervised
https://huggingface.co/datasets/jxm/bge-full-data

**Comment by jn2clark** [comment]
Awesome, thanks!

**Comment by ManuelFay** [comment]
Hello @jxmorris12 , amazing work !
I was wondering if by any chance you were planning on releasing the datasets organized by cluster ?
Fully aware we have everything to reproduce, but just in case, it would save me a bit of compute ;)
