### ISSUE TITLE
Chinese supported?

### ISSUE THREAD

**Issue by skykiseki** [jxmorris12/cde#4]
As the title suggests, I would like to know if there will be a Chinese version in the future？

**Comment by jxmorris12** [comment]
Hi, this is code for our method and training framework. You could use it on any type of data, including Chinese.

**Comment by skykiseki** [comment]
Actually, what I want to ask is, will there be a Chinese version of the pretrained CDE model released in the future?

**Comment by jxmorris12** [comment]
Oh I see! Well I'd be happy to train one for you if you provided the compute and data but otherwise I don't have any GPUs to train this with unfortunately :)
